// File templates for Phase 1A zip output.
//
// Three files emitted:
//   - site.config.js   (the per-site config)
//   - wiki/<slug>.md   (the user's main bio page)
//   - README.md        (deployment instructions for the user)

const j = (v) => JSON.stringify(v ?? "");

const yamlEscape = (s) =>
  String(s ?? "")
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"');

export function siteConfigTemplate(data) {
  const siteName = data.siteName || "Yourpedia";
  return `// Generated by Yourpedia on ${new Date().toISOString().slice(0, 10)}.
// Edit any value below; redeploy to see changes.

export const siteConfig = {
  siteName: ${j(siteName)},
  siteTagline: {
    en: "The Free Résumé",
    zh: "自由的个人百科",
  },

  homepageSlug: ${j(data.homepageSlug)},

  meta: {
    title: ${j(`${data.name} — ${siteName}`)},
    description: ${j(data.tagline || `Biographical article on ${data.name}.`)},
    ogType: "profile",
    baseUrl: ${j(data.metaBaseUrl)},
  },

  github: {
    owner: ${j(data.githubOwner)},
    repo: ${j(data.githubRepo)},
  },

  contact: {
    email: ${j(data.email || "")},
    linkedin: ${j(data.linkedin || "")},
    githubProfile: ${j(data.githubProfile || "")},
  },

  sidebar: {
    en: [
      { heading: "Notable works", items: [] },
      { heading: "Experience", items: [] },
      { heading: "Education", items: [] },
      { heading: "Concepts", items: [] },
    ],
    zh: [
      { heading: "代表作品", items: [] },
      { heading: "工作经历", items: [] },
      { heading: "教育背景", items: [] },
      { heading: "理念", items: [] },
    ],
  },

  footerEdited: {
    en: "This page is maintained by its author. See GitHub for the true edit history.",
    zh: "本页面由作者本人维护。详细修订记录见 GitHub。",
  },
};

export default siteConfig;
`;
}

export function wikiPageTemplate(data) {
  const shippedList = (data.shipped || [])
    .filter((s) => s.name)
    .map((s) =>
      s.description
        ? `- **${s.name}** — ${s.description}`
        : `- **${s.name}**`
    )
    .join("\n");

  const contactRows = [];
  if (data.email) {
    contactRows.push(`    - section: Contact`);
    contactRows.push(`    - label: Email`);
    contactRows.push(`      value: ${yamlEscape(data.email)}`);
  }
  if (data.linkedin) {
    if (!data.email) contactRows.push(`    - section: Contact`);
    const display = data.linkedin.replace(/^https?:\/\/(www\.)?/, "");
    contactRows.push(`    - label: LinkedIn`);
    contactRows.push(
      `      html: '<a href="${data.linkedin}">${display}</a>'`
    );
  }
  if (data.githubProfile) {
    if (!data.email && !data.linkedin)
      contactRows.push(`    - section: Contact`);
    const display = data.githubProfile.replace(/^https?:\/\/(www\.)?/, "");
    contactRows.push(`    - label: GitHub`);
    contactRows.push(
      `      html: '<a href="${data.githubProfile}">${display}</a>'`
    );
  }
  const contactBlock = contactRows.length ? "\n" + contactRows.join("\n") : "";

  const tagline = data.tagline || "[your one-line subtitle]";
  const bio =
    data.bio ||
    `Write your story in prose, Wikipedia-style. Use the third person. Link to other wiki pages with [[Project_One]] syntax. Pages that don't exist yet render as red links — a Wikipedia convention for "this article is coming."`;

  return `---
title: ${yamlEscape(data.name)}
subtitle: ${yamlEscape(tagline)}
description: Biographical article on ${yamlEscape(data.name)}.
infobox:
  title: ${yamlEscape(data.name)}
  image_caption: Replace /public/portrait.jpg with your photo
  rows:
    - label: Known for
      value: ${yamlEscape(tagline)}${contactBlock}
---

**${data.name}** is ${tagline.toLowerCase().startsWith("a ") || tagline.toLowerCase().startsWith("an ") ? tagline : `a ${tagline}`}.

## Career

${bio}

${
  shippedList
    ? `## Notable works\n\n${shippedList}\n`
    : ""
}
## See also

- [[Project_One]]
- [[Your_Company]]

## References

[^1]: Replace this with a real citation. LinkedIn posts, App Store
listings, product URLs, and published articles all work.
`;
}

export function readmeTemplate(data) {
  const today = new Date().toISOString().slice(0, 10);
  const siteName = data.siteName || "Yourpedia";
  return `# ${data.name}'s ${siteName}

> Generated by Yourpedia on ${today}.

This zip contains the seed of your personal Wikipedia-style résumé site,
ready to drop into a fresh fork of the
[colarpedia-template](https://github.com/wangxuzhou666-arch/colarpedia-template).

## Deploy in 5 minutes

1. **Fork the template repo** — visit
   <https://github.com/wangxuzhou666-arch/colarpedia-template> and click
   **Fork** at the top right. Name your fork whatever you want
   (e.g. \`${data.githubRepo}\`).

2. **Clone your fork locally:**

   \`\`\`bash
   git clone https://github.com/${data.githubOwner}/${data.githubRepo}.git
   cd ${data.githubRepo}
   \`\`\`

3. **Replace these files** with the ones in this zip:

   - \`site.config.js\` (overwrite)
   - \`wiki/Jane_Doe.md\` → delete, then add \`wiki/${data.homepageSlug}.md\`
   - \`wiki/Jane_Doe.zh.md\` → delete (optional; create a Chinese version later)

4. **Add your photo** at \`public/portrait.jpg\` (square, 600x600+ recommended).

5. **Commit and push:**

   \`\`\`bash
   git add .
   git commit -m "Initial setup via Yourpedia"
   git push
   \`\`\`

6. **Deploy on Vercel** — go to <https://vercel.com/new>, import your fork.
   Vercel auto-detects Next.js and deploys in ~30 seconds. Free tier is
   plenty.

## Add more pages

\`\`\`bash
touch wiki/Project_One.md
# write the page (see Jane_Doe.md in the original template for the
# frontmatter shape)
\`\`\`

Link to new pages from your bio with \`[[Project_One]]\` syntax. Pages
that don't exist yet render as red links — a Wikipedia convention.

The schema in \`CLAUDE.md\` (at the repo root) tells Claude Code how to
maintain the wiki for you. Try it: open Claude Code in the repo and ask
_"add a page about my time at <Company> and link it from ${data.homepageSlug}.md"_.

## Files in this zip

- \`site.config.js\` — your per-site config (siteName, baseUrl, GitHub repo, contact)
- \`wiki/${data.homepageSlug}.md\` — your main biography page
- \`README.md\` — this file

## Credit

- Pattern: Andrej Karpathy, _LLM Wiki_ (2026).
- Visual system: Wikipedia (Wikimedia Foundation).
- Generator: Yourpedia — open source at
  <https://github.com/wangxuzhou666-arch/colarpedia-template>.
`;
}
