// Generated by Yourpedia on 2026-05-08.
// Edit any value below; redeploy to see changes.

export const siteConfig = {
  siteName: "Yourpedia",
  siteTagline: {
    en: "The Free Résumé",
    zh: "自由的个人百科",
  },

  homepageSlug: "Xuzhou_Wang",

  meta: {
    title: "Xuzhou Wang — Yourpedia",
    description: "AI product founder and systems engineer.",
    ogType: "profile",
    baseUrl: "",
  },

  github: {
    owner: "",
    repo: "",
  },

  contact: {
    email: "xuzhou.wang.upenn@gmail.com",
    linkedin: "https://linkedin.com/in/xuzhou-wang",
    githubProfile: "",
  },

  sidebar: {
    en: [
      { heading: "Notable works", items: [] },
      { heading: "Experience", items: [] },
      { heading: "Education", items: [] },
      { heading: "Concepts", items: [] },
    ],
    zh: [
      { heading: "代表作品", items: [] },
      { heading: "工作经历", items: [] },
      { heading: "教育背景", items: [] },
      { heading: "理念", items: [] },
    ],
  },

  footerEdited: {
    en: "This page is maintained by its author. See GitHub for the true edit history.",
    zh: "本页面由作者本人维护。详细修订记录见 GitHub。",
  },
};

export default siteConfig;
