import SetupForm from "./components/SetupForm";

export const metadata = {
  title: "Yourpedia — set up your wiki in 5 minutes",
  description:
    "Fill the form, download a zip, deploy a Wikipedia-styled personal résumé site in 5 minutes. Yourpedia is a free, open template — your wiki, your repo, your domain. No SaaS lock-in.",
};

export default function SetupPage() {
  return (
    <>
      {/* Wiki-faithful top chrome (simplified — no GitHub edit links,
          no language toggle, since /setup is a tool, not an article). */}
      <div className="wiki-topbar">
        <div className="wiki-topbar-inner">
          <a href="/" className="wiki-logo">
            Yourpedia
            <span>the free résumé wiki · build yours in 5 min</span>
          </a>
        </div>
      </div>
      <div className="wiki-tabs">
        <div className="wiki-tabs-inner">
          <a href="#" className="active">
            Setup
          </a>
          <a
            href="/wiki/Jane_Doe/"
            target="_blank"
            rel="noreferrer"
            title="A placeholder wiki page generated by this template"
          >
            Live example
          </a>
          <a
            href="https://github.com/wangxuzhou666-arch/colarpedia-template"
            className="external"
            target="_blank"
            rel="noreferrer"
            title="View the open-source template on GitHub"
          >
            Source
          </a>
        </div>
      </div>

      <main className="setup-shell">
        <h1 className="wiki-title">Set up your wiki</h1>
        <p className="wiki-title-sub">
          A Wikipedia-styled personal résumé, fork-and-deploy in five minutes.
        </p>

        <p className="setup-intro">
          Fill the form below. Your browser generates a zip with a ready{"-"}
          to-drop <code>site.config.js</code> and{" "}
          <code>wiki/&lt;You&gt;.md</code>, plus a short deploy guide.
          Nothing is sent to any server &mdash; everything runs locally in
          your browser.
        </p>

        <p className="setup-meta">
          See the{" "}
          <a href="/wiki/Jane_Doe/" target="_blank" rel="noreferrer">
            placeholder example
          </a>{" "}
          for the visual style. Inspired by Andrej Karpathy&apos;s{" "}
          <a
            href="https://gist.github.com/karpathy/442a6bf555914893e9891c11519de94f"
            className="external"
            target="_blank"
            rel="noreferrer"
          >
            LLM Wiki
          </a>{" "}
          pattern.
        </p>

        <SetupForm />
      </main>

      <footer className="wiki-footer">
        <p>
          Yourpedia is a fork-and-deploy tool. Your wiki, your repo,
          your domain &mdash; nothing is locked to a SaaS.
        </p>
        <p>
          Text is available under the personal responsibility of its
          author. Yourpedia is a stylistic tribute to Wikipedia and not
          affiliated with the Wikimedia Foundation.
        </p>
      </footer>
    </>
  );
}
